### ISSUE TITLE
How to have a single hypernetwork for generating two main networks with different architectures?

### ISSUE THREAD

**Issue by sahandrez** [chrhenning/hypnettorch#5]
Hi, 
I'm fairly new to Hypernetworks, so not sure if this would be a reasonable approach. But is there a way to have a single hypernet with a conditional input, that depending on the condition, generates weights for different architectures. The architectures are not very different, for example both are MLPs, where one would have an n-dimensional output whereas the other has an m-dimensional output. 

One way I could see it implemented is to have the hypernetwork create a list of weights but then manually pick the corresponding weights of each architecture. But then this may not be that different from training two independent hypernets and so the learning may not be factorized. Would there be a better and smarter approach based on the current functionalities of the package? 

Thanks a lot! 
Sahand

**Comment by chrhenning** [comment]
Hey Sahand,

unfortunately, there is no clean way to achieve this. What I would do is the following. Assuming `m>n`. Instantiate the hyper network using the shapes of the main network with `m` outputs and with 2 conditional inputs. Write a custom `forward` wrapper that you use in your code (rather than calling `hnet.forward(...)` you could call `utils.hnet_forward(net, ...)`). Inside this custom forward method, you call `hnet.forward` and then modify the output shapes based on the condition that was inputted.

Hope that makes sense.

Best,
Christian

**Comment by sahandrez** [comment]
Hi Christian, 
Thank you for the detailed reply. Yes, it makes great sense! The package is quite well-documented and nicely implemented, adding it would be super easy for me. Thank you for this awesome tool kit! 
Best, 
Sahand
